# Netlify configuration file
# Site: griffin-radcliffe.netlify.app
# Repo: DrunkOnJava/GriffinWebsite

[build]
  publish = "public"
  command = "npm run build"

# Redirect and rewrite rules for SPA routing if needed
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Development configuration
[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "public"

# Netlify Functions if you're using them
[functions]
  directory = "netlify/functions"

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
